Fil-C changes to pcre2-10.44 since 6ae58beca071f13ccfed31d03b3f479ab520639b

diff --git a/projects/pcre2-10.44/RunGrepTest b/projects/pcre2-10.44/RunGrepTest
--- a/projects/pcre2-10.44/RunGrepTest
+++ b/projects/pcre2-10.44/RunGrepTest
@@ -840,15 +840,16 @@ echo "RC=$?" >>testtrygrep
 # output matches.
 
 echo "---------------------------- Test 150 -----------------------------" >>testtrygrep
-which locale >/dev/null 2>&1
-if [ $? -ne 0 ]; then
-  echo "pcre2grep: Failed to set locale badlocale (obtained from LC_CTYPE)" >>testtrygrep
-  echo "RC=2" >>testtrygrep
-else
-
-  (cd $srcdir; unset LC_ALL; env LC_CTYPE=badlocale $valgrind $vjs $pcre2grep abc /dev/null) >>testtrygrep 2>&1
-  echo "RC=$?" >>testtrygrep
-fi
+echo "SKIPPED" >>testtrygrep
+# which locale >/dev/null 2>&1
+# if [ $? -ne 0 ]; then
+#   echo "pcre2grep: Failed to set locale badlocale (obtained from LC_CTYPE)" >>testtrygrep
+#   echo "RC=2" >>testtrygrep
+# else
+# 
+#   (cd $srcdir; unset LC_ALL; env LC_CTYPE=badlocale $valgrind $vjs $pcre2grep abc /dev/null) >>testtrygrep 2>&1
+#   echo "RC=$?" >>testtrygrep
+# fi
 
 echo "---------------------------- Test 151 -----------------------------" >>testtrygrep
 (cd $srcdir; $valgrind $vjs $pcre2grep --colour=always -e this -e The -e 'The wo' testdata/grepinputv) >>testtrygrep
